export const fundData = [
  {
    fund_name: 'NASDAQ Cybersecurity UCITS ETF',
    primary_ticker: 'CBRS',
    income_treatment: 'Acc',
    share_class_currency: 'EUR',
    ISN: 'IE00BF16M727',
    strategy: 'Thematic',
    asset_class: 'Equity',
    region: 'Global',
    style: 'Active',
  },
  {
    fund_name: 'Cloud Computing UCITS ETF',
    primary_ticker: 'SKYE',
    income_treatment: 'Acc',
    share_class_currency: 'GBP',
    ISN: 'IE00BFD2H405',
    strategy: 'Thematic',
    asset_class: 'Equity',
    region: 'Global',
    style: 'Active',
  },
  {
    fund_name: 'Nasdaq® Clean Edge® Green Energy UCITS ETF',
    primary_ticker: 'QCLN',
    income_treatment: 'Acc',
    share_class_currency: 'EUR',
    ISN: 'IE00BDBRT036',
    strategy: 'Thematic',
    asset_class: 'Equity',
    region: 'Global',
    style: 'Active',
  },
  {
    fund_name: 'Indxx Innovative Transaction & Process UCITS ETF',
    primary_ticker: 'BLOK',
    income_treatment: 'Acc',
    share_class_currency: 'EUR',
    ISN: 'IE00BF5DXP42',
    strategy: 'Thematic',
    asset_class: 'Equity',
    region: 'Global',
    style: 'Active',
  },
  {
    fund_name: 'Dow Jones Internet UCITS ETF',
    primary_ticker: 'FDNE',
    income_treatment: 'Acc',
    share_class_currency: 'EUR',
    ISN: 'IE00BG0SSC32',
    strategy: 'Thematic',
    asset_class: 'Equity',
    region: 'United States',
    style: 'Active',
  },
  {
    fund_name: 'Dow Jones International Internet UCITS ETF',
    primary_ticker: 'FDNI',
    income_treatment: 'Acc',
    share_class_currency: 'EUR',
    ISN: 'IE00BT9PVG14',
    strategy: 'Thematic',
    asset_class: 'Equity',
    region: 'Europe',
    style: 'Active',
  },
  {
    fund_name: 'NYSE Arca Biotechnology UCITS ETF',
    primary_ticker: 'FBT',
    income_treatment: 'Acc',
    share_class_currency: 'USD',
    ISN: 'IE00BL0L0H60',
    strategy: 'Thematic',
    asset_class: 'Equity',
    region: 'Developed',
    style: 'Active',
  },
  {
    fund_name: 'IPOX® Europe Equity Opportunities UCITS ETF',
    primary_ticker: 'EFPX',
    income_treatment: 'Acc',
    share_class_currency: 'EUR',
    ISN: 'IE00BFD26097',
    strategy: 'Thematic',
    asset_class: 'Equity',
    region: 'Europe',
    style: 'Active',
  },
  {
    fund_name: 'US Equity Opportunities UCITS ETF',
    primary_ticker: 'FPXU',
    income_treatment: 'Acc',
    share_class_currency: 'USD',
    ISN: 'IE00BYTH6238',
    strategy: 'Thematic',
    asset_class: 'Equity',
    region: 'United States',
    style: 'Active',
  },
  {
    fund_name: 'FactorFX UCITS ETF',
    primary_ticker: 'FXEU',
    income_treatment: 'Acc',
    share_class_currency: 'EUR (H)',
    ISN: 'IE00BD5HBS12',
    strategy: 'Fixed Income',
    asset_class: 'Fixed Income',
    region: 'Global',
    style: 'Index',
  },
  {
    fund_name: 'FactorFX UCITS ETF',
    primary_ticker: 'FTFX',
    income_treatment: 'Acc',
    share_class_currency: 'USD',
    ISN: 'IE00BD5HBQ97',
    strategy: 'Fixed Income',
    asset_class: 'Fixed Income',
    region: 'Global',
    style: 'Index',
  },
  {
    fund_name: 'FactorFX UCITS ETF',
    primary_ticker: 'FXGB',
    income_treatment: 'Acc',
    share_class_currency: 'GBP (H)',
    ISN: 'IE00BD5HBR05',
    strategy: 'Fixed Income',
    asset_class: 'Fixed Income',
    region: 'Global',
    style: 'Index',
  },
  {
    fund_name: 'Low Duration Global Government Bond UCITS ETF',
    primary_ticker: 'FSOV',
    income_treatment: 'Dist',
    share_class_currency: 'EUR',
    ISN: 'IE00BKS2X317',
    strategy: 'Fixed Income',
    asset_class: 'Fixed Income',
    region: 'Global',
    style: 'Index',
  },
];
